### ISSUE TITLE
Unable to pan map more than 180 degrees East or West

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#102]
Is this something we want to support?

**Comment by tallytalwar** [comment]
If I am understanding the question correctly, this is because of the world bounds implementation we added to tangram-es, which makes sure user will never see outside world bounds.

We recently (today) pushed in a change for world wrapping, this will allow you to pan across world boundaries and wrap the tiles. A new build of eraser-map should pick this change from tangram library.

**Comment by ecgreb** [comment]
Fixed. Thanks @tallytalwar
