### ISSUE TITLE
Destination maneuver is not using TTS formatted verbal_pre_transition_instruction

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#137]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-481
* **What did you expected to happen?** To have the house numbers of the destination address  spoken properly.
* **What happened instead?** When arriving at the destination - the app called out "nine thousand seven hundred ninety" for the house number instead of "ninety-seven ninety" 
* **Steps to reproduce:** Here is an example url:
http://valhalla.mapzen.com/route?api_key=YOUR_KEY_HERE&json={%22locations%22:[{%22lat%22:39.390366,%22lon%22:-76.474121,%22type%22:%22break%22,%22street%22:%223J%20Cameron%20Court%22,%22city%22:%22Baltimore%22,%22state%22:%22MD%22},{%22lat%22:39.176933,%22lon%22:-76.852356,%22type%22:%22break%22,%22street%22:%229790%20Patuxent%20Woods%20Drive%22,%22city%22:%22Columbia%22,%22state%22:%22MD%22}],%22costing%22:%22auto%22,%22directions_options%22:{%22units%22:%22miles%22}}

* **produces the following destination maneuver: **
{
    "begin_shape_index": ​614,
    "time": ​0,
    "type": ​5,
    "end_shape_index": ​614,
    "instruction": "9790 Patuxent Woods Drive is on the right.",
    "length": ​0.000,
    "verbal_transition_alert_instruction": "97 90 Patuxent Woods Drive will be on the right.",
    "verbal_pre_transition_instruction": "97 90 Patuxent Woods Drive is on the right."
}
Notice the spaces in the verbal instructions

**Comment by ecgreb** [comment]
@dgearhart I am having a hard time reproducing this one since for a lot of 3 and 4 digit address numbers I am not seeing a difference in formatting for verbal instructions. For example this one:

https://valhalla.mapzen.com/route?json=%7B%22costing%22%3A%22auto%22%2C%22directions_options%22%3A%7B%22units%22%3A%22miles%22%7D%2C%22locations%22%3A%5B%7B%22lat%22%3A%2240.32239085%22%2C%22lon%22%3A%22-75.13197358%22%7D%2C%7B%22city%22%3A%22Buckingham%22%2C%22lat%22%3A%2240.347278%22%2C%22lon%22%3A%22-75.078129%22%2C%22name%22%3A%223434+Durham+Road%22%2C%22state%22%3A%22Pennsylvania%22%2C%22street%22%3A%223434+Durham+Road%22%7D%5D%7D&api_key=YOUR_KEY_HERE

The final instruction looks like this (text and verbal are the same):

```
{
begin_shape_index: 169,
time: 0,
type: 6,
end_shape_index: 169,
instruction: "3434 Durham Road is on the left.",
length: 0,
verbal_transition_alert_instruction: "3434 Durham Road will be on the left.",
verbal_pre_transition_instruction: "3434 Durham Road is on the left."
}
```

Also it appears in the code we are using only verbal formatted instructions for voice commands:

https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt

https://github.com/mapzen/on-the-road/blob/master/src/main/java/com/mapzen/valhalla/Instruction.kt#L202

**Comment by dgearhart** [comment]
@ecgreb i found the issue - the request is setting both of the destination location attributes "name" and "street" to "3434 Durham Road" - for example:
![screenshot from 2015-12-14 09 05 40](https://cloud.githubusercontent.com/assets/7515853/11783034/e229a546-a242-11e5-9662-16d30ff0f1b7.png)

the "name" should be the POI name if there is one - such as "WalMart"
The logic is:
if there is a name then output that without formatting
else if there is a street then output that with TTS formatting for the street name

when input is this:
https://valhalla.mapzen.com/route?json={%22costing%22%3A%22auto%22%2C%22directions_options%22%3A{%22units%22%3A%22miles%22}%2C%22locations%22%3A[{%22lat%22%3A%2240.32239085%22%2C%22lon%22%3A%22-75.13197358%22}%2C{%22city%22%3A%22Buckingham%22%2C%22lat%22%3A%2240.347278%22%2C%22lon%22%3A%22-75.078129%22%2C%22state%22%3A%22Pennsylvania%22%2C%22street%22%3A%223434+Durham+Road%22}]}&api_key=YOUR_KEY_HERE

![screenshot from 2015-12-14 09 19 43](https://cloud.githubusercontent.com/assets/7515853/11783208/e6c31c1c-a243-11e5-8e7a-e151e763d542.png)

then output is this:
![screenshot from 2015-12-14 09 20 48](https://cloud.githubusercontent.com/assets/7515853/11783249/3cc4fd56-a244-11e5-886e-19c36d0e5321.png)

**Comment by ecgreb** [comment]
@dgearhart thanks! Nice detective work ... will update.

**Comment by ecgreb** [comment]
We are going to need a way to determine if the `name` field for a given search result contains an actual name of if it contains the street address.

Added https://github.com/pelias/pelias-android-sdk/issues/24 to Pelias SDK project.
