### ISSUE TITLE
Multiple sizes of subway icons at certain zoom levels

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#202]
@nvkelso is this intentional? 
See screenshots
![](https://lh4.googleusercontent.com/-doEzqU3CeKQ/VnA9EJ-4bMI/AAAAAAAAW9U/GY-YK24uqOE/w671-h1193-no/2015-12-15.jpg)

![](https://lh4.googleusercontent.com/-lTOHuBP-r5Q/VnA9H74TRvI/AAAAAAAAW9g/yIoRUGkYi0s/w671-h1193-no/2015-12-15.jpg)

**Comment by blair1618** [comment]
Seems to match what's specified in the stylesheet: https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L4650-L4676

Some stations considered lower-priority are drawn smaller and without a text label.

**Comment by souperneon** [comment]
@nvkelso I believe this is confusing to the user. Can we do hide/show perhaps at higher zoom levels and prioritize the more important stations. What do you think?

**Comment by nvkelso** [comment]
This was intentional, but I agree it's not working well now (checked against a recent build). 

Ideally all the larger stations are labeled with text, but Tangram doesn't do that consistently now. Then all the smaller station icons are there to see the overall network but they're not set to label (zoom into see their labels).

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/eraser-map/commit/a9a50929e31b6fbf21987bfada6bd4214891e9dd.
