### ISSUE TITLE
Incorrect direction arrow in the instruction

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#228]
Starting point: Austerlitz, NY
Ending point: 31-19, 33rd St Astoria NY 11106

![screenshot_2016-01-03-14-08-37](https://cloud.githubusercontent.com/assets/6125224/12128520/e1bdc8a4-b3cb-11e5-8f4c-952d35d77eb0.png)

![2016-01-04 4](https://cloud.githubusercontent.com/assets/6125224/12128521/e7e7687a-b3cb-11e5-80f3-df07fcd5326d.png)

**Comment by nvkelso** [comment]
+1, I experienced this in drive tests on Friday.

**Comment by ecgreb** [comment]
This happens a lot with the first instruction in a route. I did some testing today and discovered that Valhalla is sending a maneuver type 3 (left turn) instead of type 1 (straight) for the first instruction for routes that originate at the NY office.

Request and screenshots attached below.

@dgearhart is this expected behavior?

https://valhalla.mapzen.com/route?json={"costing":"auto","directions_options":{"units":"miles"},"locations":[{"lat":"40.7445674","lon":"-73.9901808"},{"city":"Haddon","lat":"39.905573","lon":"-75.096031","name":"Pizza","state":"New%20Jersey","street":"Pizza"}]}&api_key=valhalla-XXXXXXX

As a side note I'm not sure why we are sending "Pizza" as the street :P

First instruction show left turn instead of straight arrow.

![image](https://cloud.githubusercontent.com/assets/464123/12830669/8153fa38-cb5e-11e5-957c-cd7a5aff9dc6.png)

Second instruction correctly shows right turn onto Broadway.

![image](https://cloud.githubusercontent.com/assets/464123/12830687/98df5fa8-cb5e-11e5-8089-75627ebbe0c1.png)

**Comment by ecgreb** [comment]
Incorrect ferry and roundabout icons fixed by https://github.com/mapzen/eraser-map/pull/319.

**Comment by dgearhart** [comment]
@ecgreb 
start and destination instructions - both may have side of street associated with them
we call the destination side of street out in narrative
for now, we do not explicitly call out side of street of start instruction - however, we do set it in the maneuver type
if one is in a parking lot or a building - then it could be useful
here are the maneuver types for start and destination instructions:
kStart = 1;
kStartRight = 2;
kStartLeft = 3;
kDestination = 4;
kDestinationRight = 5;
kDestinationLeft = 6;

maybe just use straight arrow for all three start types
