### ISSUE TITLE
Tilt view more in routing mode

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#249]
look at waze/ google and do something similar.

**Comment by blair1618** [comment]
The amount of tilt may not be the problem here. One big visual difference between the eraser-map style and many other maps (including Waze and Google) is that eraser-map uses an  "isometric" camera, which projects geometry such that parallel lines remain parallel. 3D maps traditionally use a "perspective" camera, in which parallel lines converge to a vanishing point. Here's a comparison of both cameras in eraser-map: on the left is our current "isometric" camera, on the right is a "perspective" camera tilted by the same amount. 

![eraser-map-cameras](https://cloud.githubusercontent.com/assets/3371850/12423720/df804416-be9a-11e5-9d95-ff118c13bb80.png)

The "perspective" camera gives much clearer visual cues of distance because it more nearly mimics the human eye, but it also sacrifices some of the distinctive styling of the eraser-map style. 

Switching between the two cameras is not difficult, it requires one changed line of YAML in the scene file and a few lines of Kotlin in eraser-map to update the position offset during routing mode.

**Comment by mjcunningham** [comment]
Ah that makes sense. Could we use this camera in routing mode but isometric elsewhere in the app? 

cc @nvkelso for map thoughts.

**Comment by tallytalwar** [comment]
It might also be tricky to change the camera for different modes.

**Comment by blair1618** [comment]
@mjcunningham I was afraid you would ask that. 

In theory yes, we can switch camera types on the fly. However we currently have no mechanism for doing this from a client application, so we would need more time to figure out how to implement that. Another minor concern (to me) is that there is way I know of to smoothly transition between these camera types.

**Comment by mjcunningham** [comment]
Cool. Let's see what @nvkelso thinks about the map then we can figure something out.

**Comment by blair1618** [comment]
We've decided to add a mechanism for Android client applications to modify the camera type of the map scene. It is long-term goal for tangram-es to allow run-time modification of any scene property, but in the short term this stop-gap will allow us to achieve a better user experience in eraser-map.

**Comment by mjcunningham** [comment]
:+1:
