### ISSUE TITLE
On map feature select pin should point to icon not building centroid.

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#254]
cc @blair1618  and @nvkelso for thoughts.

**Comment by tallytalwar** [comment]
Possibly related: https://github.com/mapzen/eraser-map/issues/150.

Refering to @nvkelso last comments on the issue.

**Comment by mjcunningham** [comment]
Not quite, see attached screenshot.

![screenshot_2016-01-19-11-47-29](https://cloud.githubusercontent.com/assets/307758/12425403/8ce33a12-bea2-11e5-8186-da45ce2b18b9.png)

**Comment by blair1618** [comment]
I think it's a much clearer user experience to create a pin precisely on the label that the user tapped. 

The reason this doesn't currently happen is because the app takes information from the tapped label, performs a pelias search on it, then puts a pin on the top search result. This process can never be guaranteed to place a pin where the user tapped. Even if the top pelias result is the exact same feature as the one the user tapped, tangram stylesheets can modify where a label is placed relative to a feature centroid and pelias cannot (and should not) have this information. 

There are multiple ways we could fix this:

1. Ignore the coordinates of the pelias search result and place a pin on the coordinates of the label (which tangram can provide)

2. Don't make a pelias request at all when responding to a tapped label. When a label is tapped, tangram provides the feature's name, coordinates, and any other properties that we have for that feature in the vector tiles. We can display this information in the "pager" and if we want to route to it we can send the coordinates that we already have directly to valhalla.

**Comment by tallytalwar** [comment]
Precisely what I wanted to discuss in the meeting today.

**Comment by tallytalwar** [comment]
Waiting on: https://github.com/pelias/pelias-android-sdk/issues/26.

Once the Pelias-android-sdk is updated, we can do Pelias search with the POI properties (`osm id` and `source`) to get appropriate results.

**Comment by mjcunningham** [comment]
https://github.com/pelias/pelias-android-sdk/pull/27 is out for a PR

**Comment by tallytalwar** [comment]
Yup, I am on it :D.

**Comment by tallytalwar** [comment]
Note: Will have some work around code to get around tiles issue: https://github.com/mapzen/vector-datasource/issues/503
