### ISSUE TITLE
Unroutable areas causes unending recalculation loop

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#334]
Device name: Asus Nexus 7 (2013)
Android Version: 6.0.1
App build number: Release 0.4
SDK: 23

I believe this may have been discussed before, but here is a local area (to @ecgreb and I) that causes this problem. When entering the highlighted parking lot, or starting a route from that parking lot, EM goes into an extremely annoying "Recalculating...Recalculating... Recalculating..." voice prompt that won't end until you get relatively close to a major road.

Sorry for re-use of previous screenshot. I didn't get a chance to take a better one because the app was so annoying that I had to stop the route so my wife wouldn't hit me :) 

![screenshot_20160207-103836](https://cloud.githubusercontent.com/assets/1163880/12873964/8a129666-cd98-11e5-8bfc-a2bbf06bd071.png)

**Comment by ecgreb** [comment]
This is definitely something we need to fix before beta but the real question is how? Let's chat about possible solutions this week.

**Comment by mjcunningham** [comment]
Seems that this was tested on an older build. Should be fixed.

**Comment by mjcunningham** [comment]
Didnt mean to close this one, too many tabs.

**Comment by mjcunningham** [comment]
Thoughts from meeting: 
- Take distance from current location to first point in route then make that the new reroute tolerance
- tell user to proceed to highlighted route

**Comment by mjcunningham** [comment]
![image](https://cloud.githubusercontent.com/assets/307758/13089289/f4600b44-d4bd-11e5-9ac7-9bd7e4991779.png)

**Comment by zerebubuth** [comment]
I experienced a similar "recalculating loop" when I deviated from the suggested route (although still on the road). I think any delay may just have been due to network slowness. Hearing "recalculating" in a loop is pretty distracting. Is there any way to get it to only play the sound once, or at least only once every 10s?

Background: I was heading south on the A406 towards [Hanger Lane gyratory](http://www.openstreetmap.org/#map=17/51.53090/-0.29274), and Eraser Map wanted me to continue south to the M4 along Hanger Lane, but I turned west onto the A40 (Western Avenue). I'm not sure the routing instruction was wrong - continuing south there is a perfectly good route, I just prefer the A40 as it's generally less busy.
