### ISSUE TITLE
Reroute routeline always has junk initial node geom

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#374]
When I go into a reroute state in master-907 and earlier, I notice that the new routeline geometry I see on screen always includes some non-OSM-way-snapped node at the beginning, and then the next node is snapped-on-OSM-way at an angle. I think we should only see the snapped geoms for the entire routeline. 

Is this an Eraser Map app logic thing or upstream in Valhalla?

![screenshot_2016-02-14-14-31-02](https://cloud.githubusercontent.com/assets/853051/13068933/ecce7976-d434-11e5-8448-43782294609b.png)

**Comment by ecgreb** [comment]
The route geometry comes from Valhalla. The app just decodes what comes back in the response. I don't see any code that would prepend a starting location in on-the-road or erasermap.

https://github.com/mapzen/on-the-road/blob/master/src/main/java/com/mapzen/valhalla/Route.kt#L147

https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt#L379

**Comment by nvkelso** [comment]
@kevinkreiser for comment?

**Comment by kevinkreiser** [comment]
first thing yeah, we shouldn't ever pass you a point that isnt somewhere along OSM geometry..

which is why i was really hoping to see something that sent the position of the on screen arrow icon (current gps) position to tangram followed by the route geometry. i'm no expert at kotlin, but it looks like it just copies route geometry into an empty list and passes that on to tangram..

so... looking at the Route.kt to see if somehow something could get in the route geometry... nothing stands out to me there, i see that polyline decoding was modified to include information at each point along the path (likely to aid in updating the persons progress along the route as they move) but other than that i dont see any extra stuff being added...

perhaps this is a new bug in valhalla, ill take a look!

**Comment by kevinkreiser** [comment]
ok so i had a quick look over the code that produces the shape in valhalla. it didnt see any recent changes there nor did anything look wrong, so, can someone give me a re-route request from the app that has been confirmed to display like this? if its too much trouble i can keep trying stuff on my end as well.

**Comment by ecgreb** [comment]
So far I have not been able to reproduce. Seems like this is pretty low priority if it only happens on reroutes and only some of the time. Maybe I need to test at more weird angle intersections.
