### ISSUE TITLE
Make 'Start Navigation' look like a button with a background color

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#385]
#06a6d4 background color

Example:
![9](https://cloud.githubusercontent.com/assets/6125224/13161290/d2356fc4-d66a-11e5-84fd-5b40c4cd1c07.png)

**Comment by sarahlensing** [comment]
Added background blue color because style of app has changed since ticket was created

![screenshot_2016-02-29-12-44-22](https://cloud.githubusercontent.com/assets/494323/13403376/b220ec56-dee2-11e5-8888-f511e431661f.png)
![screenshot_2016-02-29-12-44-28](https://cloud.githubusercontent.com/assets/494323/13403377/b4606f00-dee2-11e5-965f-669a0e402ad0.png)

**Comment by mjcunningham** [comment]
:+1:
