### ISSUE TITLE
Route preview buttons need pressed state

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#459]
"View List" and "Start Navigation" buttons no longer have a pressed state that visually responds to user touch.

**Comment by souperneon** [comment]
Related… can we make the colors match the comps?
The blue for the 'start navigation' is fine but the 'view list' button should be white with just a grey outline.
We can make the outline for the start button be the same as the fill to match the size.

**Comment by sarahlensing** [comment]
@souperneon What background, text, and border colors do you want for the pressed states? Where is a link to the most recent comp?

**Comment by souperneon** [comment]
@sarahlensing I made the changes to button colors (the PR you merged). I was thinking we make tap/press states the same for every button and icon. The grey pulsing circle thing thats the Android default. We can assume all icon areas are square
We should add it to
- Settings
- List view
- Map view
- switch start and destination
- view list button
- start navigation button
- preview button
- settings 
- back arrow
- cancel

What do you recommend for tapping list items? Like in autocomplete or search results list or directions list? I'll be ok if we want to use the same behavior there as well. :)

**Comment by souperneon** [comment]
Related https://github.com/mapzen/eraser-map/issues/327

**Comment by sarahlensing** [comment]
@souperneon I think keeping all the tap states the same makes sense for list items, autocomplete, search, settings, directions...I think that for the Start Navigation button, a gray pressed state might feel abrupt, maybe we want to make the color a darker blue than the normal blue bg in the normal state? I'm happy to make them all gray but feel like it might be better for this button to be an exception from the lists states because the Start Navigation's bg and text colors are different.

**Comment by souperneon** [comment]
You're right! I was thinking for the button with the colored background, more like all the Google apps like Gmail or Calendar, their floating buttons have colored background with the grey ripple. But because its a color it gives the illusion that the color got darker. I can show you what I mean if my words are totally confusing… :|
