### ISSUE TITLE
Use confidence score to influence reverse geocoding

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#524]
Currently, the user taps the map, we send the coordinates to pelias, then drop the pin on the map where we get coordinates back from /reverse. This breaks down in areas with limited data coverage becuase the user will have their finger in one spot and we'll drop the pin in another. 

We can fix this by using the [confidence](https://mapzen.com/documentation/search/reverse/#confidence-scores-for-the-results) feature in pelias. 

We can drop the pin on the map where the user taps then send the coordinates to pelias. Based on the confidence score, we can alter the display text to say "Dropped pin _near_ feature XYZ" rather than snapping the pin to feature XYZ.

**Comment by mjcunningham** [comment]
I'm going to close the 2 issues floating around about this in favor of this issue. 
https://github.com/mapzen/eraser-map/issues/150
https://github.com/mapzen/eraser-map/issues/514

**Comment by caioiglesias** [comment]
I was about to report on it. Since I already wrote the issue I'll just leave it here.

* **Device name:** Galaxy S6 Edge Plus 
* **Android Version:** 5.1.1
* **App build number:** 0.7.6
* **What did you expected to happen?** I'd expect it to drop a marker precisely at the location of the long press.
* **What happened instead?** The map centers at a "nearby" POI or address usually blocks away.
* **Steps to reproduce:** Go to any city in Brazil and long press on the map. I've tried it in Sao Paulo, SP, Brazil.
