### ISSUE TITLE
./app/build.gradle misses one option

### ISSUE THREAD

**Issue by almereyda** [mapzen/eraser-map#548]
- **Device name:** Sony Xperia Z5
- **Android Version:** 6.0
- **App build number:** 0.8.1
- **What did you expected to happen?** Being able to configure the `BASE_URL` for vector tiles, too. Also a matching naming between `BASE_URL`s and `API_KEY`s would make initial understanding easier.
- **What happened instead?** `./app/build.gradle` only contains `BASE_URL` parameters for `PELIAS` and `VALHALLA`. Both are interchangeably named `SEARCH` and `ROUTE` for the `API_KEY` parameters.
- **Steps to reproduce:** Look at `./app/build.gradle`
- **Attach a screenshot** No.
- **Attach device logs** No.

**Comment by ecgreb** [comment]
Thanks for the report. Yes we should totally standardize the names used for keys/urls in `build.gradle`. This is what you get when you build an app against services that change names during development :) 

Updating the base URL for tiles is a little trickier since this lives in the scene file submodule but we will be adding that ability in a future release.
