### ISSUE TITLE
Add make target to pull in mobile branch of Tangram scene assets on build

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#67]
We need a better way to pull over changes from the Tangram eraser-map repo, and target those with a `mobile` branch.

See also:

* https://github.com/tangrams/eraser-map/issues/54

**Comment by nvkelso** [comment]
We had talked about @blair1618 doing this?

**Comment by bcamper** [comment]
Yeah, maybe either:

- git submodule 
- build script that copies the scene file from remote repo

I'll let @blair1618 weigh in.

**Comment by tallytalwar** [comment]
@karim Also had some ideas of targeting a tangram binary (build from travis) with another branch with eraser-map repo.

**Comment by karimnaaji** [comment]
What I was thinking (or @karim's idea, not sure anymore!) wasn't totally related to this actually; I was suggesting a way to easily provide a .app or executable on a separate branch of the tangram-es repo (*gh-pages* for example), so that we could download the latest .app and use to test content / stylesheet faster than using and deploying the .apk ([trello-ticket](https://trello.com/c/v7YZIk1P/679-auto-deploy-tangram-es-compiled-binaries) for this).
Using a git submodules or a script like @bcamper  mentioned would make more sense for that issue.

**Comment by karim** [comment]
I think you got the wrong @karim :)

**Comment by ecgreb** [comment]
Submodule is probably easiest to get things up and running provided the mobile stylesheet and assets can live in their own repo.

**Comment by ecgreb** [comment]
Resolved by https://github.com/mapzen/eraser-map/pull/70.
