### ISSUE TITLE
Incorrect Transit Line color

### ISSUE THREAD

**Issue by tigerlily-he** [mapzen/eraser-map#697]
![screenshot_20160721-103837](https://cloud.githubusercontent.com/assets/13492525/17027178/e3e44c74-4f30-11e6-8866-a6bc462edbd4.png)
* **Device name: Nexus 6** 
* **Android Version: 6.0.1** 
* **App build number: 0.10.2** 
* **What did you expected to happen? Indicate 6 train line as green** 
* **What happened instead? The color was purplish-gray (see screenshot)**
* **Steps to reproduce: Get direction for somewhere on the Upper East Side**

If something happened while you were routing, share with us:

* **Where were you? Samsung Accelerator, NYC**
* **Routing from origin: 30 W 26th street, NYC**
* **Routing to destination: 1534 3 Avenue**

**Comment by mjcunningham** [comment]
cc @sarahlensing @drewda 

Where can we verify the line color coming from transitland?

**Comment by sarahlensing** [comment]
@mjcunningham the color is actually coming from valhalla. the best way to verify is to download a dev build (so that the logs are visible) and in AndroidStudio, search for "retrofit" in the AndroidMontior tab

<img width="1245" alt="screen shot 2016-07-21 at 10 51 01 am" src="https://cloud.githubusercontent.com/assets/494323/17031369/0d0b66a0-4f31-11e6-942a-1cf3b03e6fd7.png">

**Comment by ecgreb** [comment]
There error here is in the way we are parsing the color value returned by valhalla.

https://github.com/mapzen/on-the-road/blob/master/library/src/main/java/com/mapzen/valhalla/Instruction.kt#L259

Valhalla returns an integer (base 10) value for the line color. In this case the value is `color: 37692`. The problem is when we convert that to hex it produces a 4 digit value in hexidecimal `933C` which unfortunately is an invalid hex color.

It seems Android renders this 4 digit value as a pale purple when Tangram ignores it (entire route line on map is default color).

When we get a color value that is less than 6 digits when converted to hex we just need to preprend zeros to the color string. For example `#933C` becomes `#00933C` which seems to produce the correct shade of green for the 6 train to the upper east side.

**Comment by ecgreb** [comment]
I created an issue here. Fix will be up shortly.

https://github.com/mapzen/on-the-road/issues/86

**Comment by drewda** [comment]
Sounds like this issue is internal on your side, but in the future if there are questions about the source data:

1. find a route Onestop ID in the Turn-by-Turn response. For example: `r-9q9-local`
2. open up http://transit.land/api/v1/routes/r-9q9-local or http://transit.land/api/v1/routes/r-9q9-local.geojson
3. look for `route_color`
4. and if that fails, feel free to ping me!

Alternatively, Meghan will soon be sharing the Mobility Explorer tool, which will make this an even simpler process to check in a GUI.

**Comment by ecgreb** [comment]
Thanks for the info @drewda. I believe we have a fix in place but this will certainly be helpful for the future.

Here is a screenshot testing the app with https://github.com/mapzen/on-the-road/pull/87

![image](https://cloud.githubusercontent.com/assets/464123/17039626/6284de4e-4f69-11e6-8f5d-76be1cf325c0.png)

![image](https://cloud.githubusercontent.com/assets/464123/17039592/40041984-4f69-11e6-9351-3a39eda18a7e.png)
