### ISSUE TITLE
Client data lost after rotation in routing mode

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#709]
Rotating the device in navigation mode causes all client data (route line, marker, and pins) to be lost. Also map zoom level is reset to 0.

No new client data is able to be added after this occurs but for some reason the find me marker is still available.

Needs more investigation to see why only the find me marker works also to determine if the zoom issue is in the app, Mapzen SDK, or Tangram.

**Comment by sarahlensing** [comment]
I believe this is a Tangram 0.4 issue. 

To reproduce, checkout 9cb98d106f493a94bdc11340edfd66f62d36b578 on master in the Mapzen Android SDK, and rotate the device when in the "Basic Map" example. The map zoom resets to zero. Then checkout 880d750dffc8b761d984b4d3539d0858f8d1b20c (which uses Tangram 0.3.2) and see that the issue doesn't exist. See here the changes between these two commits are only to gradle.properties and installation.md (https://github.com/mapzen/android/commits/master)

I tested this on a Samsung Galaxy S6 Edge running 6.0.1.

Tangram 0.4 (9cb98d106f493a94bdc11340edfd66f62d36b578)
https://www.dropbox.com/s/8qehq1pgx65svz3/2016_07_27_11_05_48.mp4?dl=0

Tangram 0.3.2 (880d750dffc8b761d984b4d3539d0858f8d1b20c)
https://www.dropbox.com/s/a040om8w4zzo0oo/2016_07_27_10_51_42.mp4?dl=0

cc @blair1618 @tallytalwar

**Comment by blair1618** [comment]
Part of this is expected, intentional behavior that was introduced in 0.4 - see the last bullet point of the release notes: https://github.com/tangrams/tangram-es/releases/tag/0.4-android

It should not be the case that you can't add more data after the activity is re-created. That may be because the `MapData` objects are static and are therefore held longer than the `MapController` that they were created from: https://github.com/mapzen/android/blob/master/library/src/main/java/com/mapzen/android/OverlayManager.java#L95-L105

**Comment by ecgreb** [comment]
Good catch on the static vars. We should investigate the implications of this.

Also I never know you could created a highlight link for multiple lines in github!

**Comment by sarahlensing** [comment]
Neither did I, thats a nice feature!
